import os
import json

# --- CONFIGURATION ---
# The directory containing your images
SOURCE_DIR = 'sorted_ducks_and_bunnies_dataset' 
# The output JavaScript file name
OUTPUT_FILE = 'image_file_lists.js'
# Allowed file extensions
EXTENSIONS = ('.jpg')

def generate_file_lists():
    rabbit_paths = []
    duck_paths = []

    # Walk through the directory tree
    for root, _, files in os.walk(SOURCE_DIR):
        for filename in files:
            if filename.lower().endswith(EXTENSIONS):
                # Create the relative path
                full_path = os.path.join(root, filename)
                
                # Convert backslashes to forward slashes for JavaScript/Web compatibility
                web_path = full_path.replace(os.sep, '/')

                # --- CATEGORIZATION LOGIC ---
                # Checks if 'rabbit' or 'duck' is in the folder path or filename
                if 'rabbit' in web_path.lower():
                    rabbit_paths.append(filename)
                elif 'duck' in web_path.lower():
                    duck_paths.append(filename)

    # Prepare the JavaScript content
    # json.dumps ensures the lists are formatted as valid JS arrays
    # Note: get more rabbit files
    js_content = f"""// This file is auto-generated by the Python script
const RABBIT_FILES = {json.dumps(rabbit_paths, indent=4)};

const DUCK_FILES = {json.dumps(duck_paths, indent=4)};
"""

    # Write to the .js file
    try:
        with open(OUTPUT_FILE, 'w') as f:
            f.write(js_content)
        print(f"Success! Generated '{OUTPUT_FILE}'")
        print(f"Found {len(rabbit_paths)} Rabbit files and {len(duck_paths)} Duck files.")
    except IOError as e:
        print(f"Error writing file: {e}")

if __name__ == "__main__":
    generate_file_lists()